stages:
  - build
  - install
  - publish

build-job:
  image: golang:latest
  stage: build
  needs: []
  before_script:
    - apt-get update
    - apt-get install -y make
  script:
    - make touchlog
    - ./touchlog --version --verbose

install-job:
  image: golang:latest
  stage: install
  dependencies:
    - build-job
  needs: ["build-job"]
  before_script:
    - apt-get update
    - apt-get install -y make
  script:
    - make install
    - touchlog --version --verbose

publish-job:
  image: golang:latest
  stage: publish
  only:
    - tags
  dependencies:
    - install-job
  needs: ["install-job"]
  before_script:
    - apt-get update
    - apt-get install -y make ncftp pandoc git
  script:
    - make publish
    - ./ftp.sh
