stages:
  - build
  - publish
  - release

build-job:
  image: golang:latest
  stage: build
  only:
    - branches
  needs: []
  before_script:
    - apt-get update
    - apt-get install -y make
  script:
    - make touchlog
    - ./touchlog --version --verbose

install-job:
  image: golang:latest
  stage: build
  needs: []
  before_script:
    - apt-get update
    - apt-get install -y make
  script:
    - make install
    - which touchlog
    - touchlog --version --verbose

package-job:
  image: golang:latest
  stage: publish
  only:
    - branches
  dependencies:
    - install-job
  needs: ["install-job"]
  before_script:
    - apt-get update
    - apt-get install -y make pandoc git tar
  script:
    - make package
    - cd dist
    - tar cvf touchlog-$CI_COMMIT_SHORT_SHA.tar README.md touchlog LICENSE
    - tar cvf touchlog-$CI_COMMIT_SHORT_SHA-src.tar README.md touchlog LICENSE touchlog.1 touchlog.go
    - cp touchlog-$CI_COMMIT_SHORT_SHA.tar touchlog-latest.tar
    - cp touchlog-$CI_COMMIT_SHORT_SHA-src.tar touchlog-latest-src.tar
    - cd ..
  artifacts:
    expose_as: "source"
    paths:
      - dist/touchlog-latest.tar
      - dist/touchlog-latest-src.tar

publish-job:
  image: golang:latest
  stage: publish
  only:
    - tags
  dependencies:
    - install-job
  needs: ["install-job"]
  before_script:
    - apt-get update
    - apt-get install -y make ncftp pandoc git tar ncftppush
  script:
    - make publish
    - cd dist
    - tar cvf touchlog-$CI_COMMIT_TAG.tar README.md touchlog LICENSE
    - tar cvf touchlog-$CI_COMMIT_TAG-src.tar README.md touchlog LICENSE touchlog.1 touchlog.go
    - cp touchlog-$CI_COMMIT_TAG.tar touchlog-latest.tar
    - cp touchlog-$CI_COMMIT_TAG-src.tar touchlog-latest-src.tar
    - cd ..
    - ./ftp.sh
  artifacts:
    paths:
      - dist/touchlog-latest.tar
      - dist/touchlog-latest-src.tar

release-job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  only:
    - tags
  dependencies:
    - publish-job
  needs: ["publish-job"]
  script:
    - echo release job
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Release $CI_COMMIT_TAG'
    description: './CHANGELOG.md'
