stages:
  - build
  - publish

build-job:
  image: gcc:bookworm
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y make gcc pandoc
  script:
    - make publish
  artifacts:
    untracked: true

publish-job:
  image: gcc:bookworm
  stage: publish
  dependencies:
    - build-job
  only:
    - master
  before_script:
    - apt-get update
    - apt-get install -y ncftp
  script:
    - ./ftp.sh

