stages:
  - build
  - publish

build-job:
  image: golang:latest
  stage: build
  needs: []
  before_script:
    - apt-get update
    - apt-get install -y make
  script:
    - make build
  artifacts:
    untracked: true

publish-job:
  image: golang:latest
  stage: publish
  only:
    - master
  dependencies:
    - build-job
  needs: ["build-job"]
  before_script:
    - apt-get update
    - apt-get install -y make ncftp pandoc
  script:
    - make publish
    - ./ftp.sh
    - ./publish.sh
