version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

run:
  relative-path-mode: wd

issues:
  # 0 = unlimited (intentional - fail on any issues)
  max-issues-per-linter: 0
  max-same-issues: 0

