version: 2

project_name: touchlog

builds:
  - id: touchlog
    main: ./cmd/touchlog
    binary: touchlog
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  use: git-chglog
  use_config: .chglog/config.yml

release:
  mode: replace
  header: |
    ## {{ .Tag }}

    {{ if .ReleaseNotes }}
    {{ .ReleaseNotes }}
    {{ else }}
    Release {{ .Tag }}
    {{ end }}

  footer: |
    ## Installation

    Download the appropriate binary for your platform and extract it:

    ```bash
    # Linux
    tar -xzf touchlog_{{ .Version }}_linux_amd64.tar.gz
    # or
    tar -xzf touchlog_{{ .Version }}_linux_arm64.tar.gz

    # macOS
    tar -xzf touchlog_{{ .Version }}_darwin_amd64.tar.gz
    # or
    tar -xzf touchlog_{{ .Version }}_darwin_arm64.tar.gz
    ```

    Then move the binary to a directory in your PATH:

    ```bash
    sudo mv touchlog /usr/local/bin/
    ```

